FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Sensor/Sensor.csproj", "Sensor/"]
RUN dotnet restore "Sensor/Sensor.csproj"
COPY . .
WORKDIR "/src/Sensor"
RUN dotnet build "Sensor.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Sensor.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Sensor.dll"]
